//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_muchocphi
    {
        public int id { get; set; }
        public int muchocphi { get; set; }
        public int hocky { get; set; }
        public int namhoc_id { get; set; }
    }
}
