//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hinhthuc_khenthuong
    {
        public int id { get; set; }
        public Nullable<int> ma { get; set; }
        public string cancukhenthuong { get; set; }
        public string lido { get; set; }
        public string hinhthuckhenthuong { get; set; }
        public string soquyetdinh { get; set; }
        public string nguoibanhanh { get; set; }
        public Nullable<System.DateTime> ngaybanhanh { get; set; }
    }
}
