//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hinhthuc_kyluat
    {
        public int id { get; set; }
        public Nullable<int> ma_nguoi { get; set; }
        public string vipham { get; set; }
        public Nullable<System.DateTime> thoigianxayra { get; set; }
        public string diadiem { get; set; }
        public string mota { get; set; }
        public string nguoichungkien { get; set; }
        public string hinhthuc_vipham { get; set; }
        public string hinhthuc_kyluat1 { get; set; }
        public Nullable<bool> giaithic { get; set; }
        public string lido { get; set; }
        public string soquyetdinh { get; set; }
        public string nguoibanhanh { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    }
}
