//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocbong
    {
        public int ID { get; set; }
        public Nullable<int> sv_id { get; set; }
        public Nullable<double> Diemtb { get; set; }
        public Nullable<int> LoaiHB_id { get; set; }
        public Nullable<double> MucHB { get; set; }
        public Nullable<int> hocky { get; set; }
        public Nullable<int> namhoc { get; set; }
        public string Ghichu { get; set; }
    }
}
