//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocphan_quanhe
    {
        public int id { get; set; }
        public Nullable<int> khung_hp_id { get; set; }
        public Nullable<int> hp_id { get; set; }
        public Nullable<int> hp_quanhe_trc { get; set; }
        public Nullable<int> loaihp_quanhe_id { get; set; }
        public Nullable<int> id_nhom { get; set; }
        public Nullable<sbyte> and { get; set; }
        public Nullable<sbyte> or { get; set; }
    }
}
