//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocphi
    {
        public int ID { get; set; }
        public Nullable<int> sv_id { get; set; }
        public Nullable<double> Hocphi1 { get; set; }
        public Nullable<double> HocphiHL { get; set; }
        public Nullable<double> MucGiam { get; set; }
        public Nullable<int> doituongmiengiam_id { get; set; }
        public Nullable<byte> Tatca { get; set; }
        public Nullable<double> TienGiam { get; set; }
        public Nullable<double> HocBong { get; set; }
        public Nullable<double> HocphiCong { get; set; }
        public Nullable<double> HocphiCon { get; set; }
        public Nullable<double> HocphiNo { get; set; }
        public Nullable<double> HocphiThua { get; set; }
        public Nullable<double> Dathu { get; set; }
        public Nullable<double> Dachi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoHP { get; set; }
        public Nullable<int> SoHPHL { get; set; }
        public Nullable<int> SoTinchi { get; set; }
        public Nullable<int> SoTinchiHL { get; set; }
        public string ListHP { get; set; }
        public string ListHPHL { get; set; }
        public Nullable<double> CUSBTT { get; set; }
        public Nullable<double> CUSBYT { get; set; }
        public Nullable<double> CUSSTS { get; set; }
        public Nullable<double> CUSAV { get; set; }
        public Nullable<double> CUSKSK { get; set; }
        public Nullable<double> CUSQP { get; set; }
        public Nullable<byte> Chono { get; set; }
        public Nullable<double> Daukhoa { get; set; }
        public Nullable<byte> Daukhoa_T { get; set; }
        public Nullable<double> DuDaukhoa { get; set; }
        public Nullable<byte> DuDaukhoa_T { get; set; }
        public Nullable<byte> CUSAV_T { get; set; }
        public Nullable<byte> CUSBTT_T { get; set; }
        public Nullable<byte> CUSBYT_T { get; set; }
        public Nullable<byte> CUSKSK_T { get; set; }
        public Nullable<byte> CUSQP_T { get; set; }
        public Nullable<byte> CUSSTS_T { get; set; }
        public Nullable<byte> UQuyen { get; set; }
        public Nullable<double> Tongthu { get; set; }
    }
}
