//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocphan
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string TenVT { get; set; }
        public string ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> nganh_id { get; set; }
        public string GhiChu { get; set; }
        public string Mota { get; set; }
    }
}
