//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocvu_test
    {
        public int id { get; set; }
        public Nullable<int> hocky { get; set; }
        public Nullable<int> namhoc { get; set; }
        public Nullable<int> id_sv { get; set; }
        public Nullable<double> diemTB4 { get; set; }
        public Nullable<double> diemTB10 { get; set; }
        public Nullable<double> diemHB { get; set; }
        public Nullable<double> diemTL4 { get; set; }
        public Nullable<double> diemTL10 { get; set; }
        public Nullable<int> soTCDK { get; set; }
        public Nullable<int> soTCMoi { get; set; }
        public Nullable<int> soTCHoclai { get; set; }
        public Nullable<int> xuly { get; set; }
        public string ghichu { get; set; }
    }
}
