//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocvu
    {
        public int ID { get; set; }
        public Nullable<int> hk_id { get; set; }
        public Nullable<int> hocky { get; set; }
        public Nullable<int> namhoc { get; set; }
        public Nullable<int> sv_id { get; set; }
        public Nullable<int> HPDangky { get; set; }
        public Nullable<double> DiemTBHT { get; set; }
        public Nullable<double> DiemTBHT10 { get; set; }
        public Nullable<double> DiemTBHB { get; set; }
        public string XepLoai { get; set; }
        public Nullable<int> HPTichluy { get; set; }
        public Nullable<double> DiemTBTL { get; set; }
        public Nullable<int> HPBatbuoc { get; set; }
        public Nullable<int> SoTCHoclai { get; set; }
        public string XepLoaiCK { get; set; }
        public Nullable<double> DiemTB2Ky { get; set; }
        public Nullable<double> DiemRL { get; set; }
        public Nullable<double> DiemRLCK { get; set; }
        public Nullable<int> HPhoclai { get; set; }
        public string Ghichu { get; set; }
        public string Xuly { get; set; }
    }
}
