//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoso_sv
    {
        public int ID { get; set; }
        public string STT { get; set; }
        public string ma { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public Nullable<byte> gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string noisinh { get; set; }
        public Nullable<int> nganh_id { get; set; }
        public Nullable<int> lop_id { get; set; }
        public Nullable<int> chucvu_id { get; set; }
        public Nullable<int> dantoc_id { get; set; }
        public Nullable<int> tongiao_id { get; set; }
        public string quequan { get; set; }
        public string diachi { get; set; }
        public string didong { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string cmnd { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string noicap { get; set; }
        public string cha { get; set; }
        public string me { get; set; }
        public Nullable<int> tp_giadinh_id { get; set; }
        public Nullable<int> tp_banthan_id { get; set; }
        public string quatrinh { get; set; }
        public Nullable<int> chucvu_doanthe_id { get; set; }
        public Nullable<byte> doan { get; set; }
        public Nullable<System.DateTime> ngay_doan { get; set; }
        public Nullable<byte> dang { get; set; }
        public Nullable<System.DateTime> ngay_dang { get; set; }
        public Nullable<System.DateTime> ngay_chinhthuc { get; set; }
        public Nullable<int> ngoaingu_id { get; set; }
        public Nullable<int> quoctich_id { get; set; }
        public Nullable<System.DateTime> ngay_nhaphoc { get; set; }
        public Nullable<double> diem_dauvao { get; set; }
        public Nullable<int> doituong_id { get; set; }
        public string ts_sbd { get; set; }
        public Nullable<int> ts_khuvuc_id { get; set; }
        public Nullable<int> nam_totnghiep { get; set; }
        public string tro_diachi { get; set; }
        public string tro_dienthoai { get; set; }
        public Nullable<System.DateTime> tamtru_ngay { get; set; }
        public Nullable<byte> tamtru_dk { get; set; }
        public Nullable<int> nganhang_id { get; set; }
        public string anh { get; set; }
        public string nganhang_sotk { get; set; }
        public string ghichu { get; set; }
    }
}
