//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoso_cb
    {
        public int ID { get; set; }
        public string STT { get; set; }
        public string ma { get; set; }
        public Nullable<int> bp_id { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public Nullable<byte> gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string noisinh { get; set; }
        public string quequan { get; set; }
        public string truquan { get; set; }
        public Nullable<int> dantoc_id { get; set; }
        public Nullable<int> tongiao_id { get; set; }
        public Nullable<int> doituong_id { get; set; }
        public Nullable<int> quoctich_id { get; set; }
        public string cmnd { get; set; }
        public Nullable<System.DateTime> ngay_cap { get; set; }
        public string noicap { get; set; }
        public Nullable<int> tp_giadinh_id { get; set; }
        public Nullable<int> tp_banthan_id { get; set; }
        public Nullable<System.DateTime> ngay_congtac { get; set; }
        public Nullable<System.DateTime> ngay_nhapngu { get; set; }
        public Nullable<System.DateTime> ngay_xuatngu { get; set; }
        public Nullable<System.DateTime> ngay_vaonganh { get; set; }
        public Nullable<System.DateTime> ngay_vaocoquan { get; set; }
        public Nullable<int> chucvu_doanthe_id { get; set; }
        public Nullable<sbyte> doan { get; set; }
        public Nullable<System.DateTime> ngay_doan { get; set; }
        public Nullable<sbyte> dang { get; set; }
        public Nullable<System.DateTime> ngay_dang { get; set; }
        public Nullable<System.DateTime> ngay_chinhthuc { get; set; }
        public string noivao_dang { get; set; }
        public string nguoigt1 { get; set; }
        public string nguoigt2 { get; set; }
        public Nullable<sbyte> thuongbinh { get; set; }
        public Nullable<sbyte> giadinhlietsi { get; set; }
        public Nullable<byte> huongTBLS { get; set; }
        public string trinhdo_hocvan { get; set; }
        public string trinhdo_chuyenmon { get; set; }
        public string hethong_daotao { get; set; }
        public Nullable<int> nam_totnghiep { get; set; }
        public Nullable<int> nganh_id { get; set; }
        public Nullable<int> ngoaingu_id { get; set; }
        public Nullable<int> chucvu_id { get; set; }
        public string bhxh_so { get; set; }
        public Nullable<System.DateTime> bhxh_ngaycap { get; set; }
        public string bhxh_noi { get; set; }
        public Nullable<System.DateTime> bhxh_ngaydong { get; set; }
        public Nullable<double> bhxh_mucdong { get; set; }
        public string suckhoe { get; set; }
        public string nhanxet { get; set; }
        public string tunhanxet { get; set; }
        public string TrinhdoChinhtri { get; set; }
        public Nullable<int> hocham_id { get; set; }
        public Nullable<int> hocvi_id { get; set; }
        public string Diachi { get; set; }
        public string Mobile { get; set; }
        public string Dienthoai { get; set; }
        public string Email { get; set; }
        public string anh { get; set; }
        public Nullable<sbyte> is_giangvien { get; set; }
        public Nullable<int> nganhang_id { get; set; }
        public string nganhang_sotk { get; set; }
        public string ghichu { get; set; }
    }
}
