//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khung_hp
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string ma { get; set; }
        public Nullable<int> khung_id { get; set; }
        public Nullable<int> hp_id { get; set; }
        public Nullable<long> sotc { get; set; }
        public Nullable<long> lythuyet { get; set; }
        public Nullable<int> thuchanh { get; set; }
        public Nullable<long> doan { get; set; }
        public string mota { get; set; }
        public string motahoctruoc { get; set; }
        public Nullable<int> hocky { get; set; }
    }
}
