//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lop
    {
        public int ID { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> khung_id { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> ht_daotao_id { get; set; }
        public Nullable<int> capdaotao_id { get; set; }
        public Nullable<long> id_gv { get; set; }
        public Nullable<byte> Locked { get; set; }
        public Nullable<int> nganh_id { get; set; }
        public Nullable<int> namnhaphoc { get; set; }
    }
}
