//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lop_gvcn
    {
        public int ID { get; set; }
        public Nullable<int> lop_id { get; set; }
        public Nullable<int> gv_id { get; set; }
        public string Hocky { get; set; }
    }
}
