//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lophocphandiem
    {
        public int id { get; set; }
        public Nullable<int> idlop { get; set; }
        public Nullable<sbyte> idcotdiem { get; set; }
        public Nullable<double> heso { get; set; }
    }
}
