//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lophocphan
    {
        public int ID { get; set; }
        public string STT { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> hocphan_id { get; set; }
        public Nullable<int> giaovien_id { get; set; }
        public Nullable<int> donvi_id { get; set; }
        public Nullable<int> namhoc_id { get; set; }
        public Nullable<int> hocky { get; set; }
        public Nullable<int> soluong { get; set; }
    }
}
