//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lophpdanhsach
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> lophocphan_id { get; set; }
        public Nullable<int> masv { get; set; }
        public Nullable<int> diemcc { get; set; }
        public Nullable<int> diembt { get; set; }
        public Nullable<int> diemgk { get; set; }
        public Nullable<int> diemck { get; set; }
        public Nullable<int> diemdoan { get; set; }
        public Nullable<float> diemtrungbinh { get; set; }
    }
}
