//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lophp
    {
        public int ID { get; set; }
        public Nullable<int> idlop { get; set; }
        public string masv { get; set; }
        public Nullable<double> diem1 { get; set; }
        public Nullable<double> diem2 { get; set; }
        public Nullable<double> diem3 { get; set; }
        public Nullable<double> diem4 { get; set; }
        public Nullable<double> diem5 { get; set; }
        public Nullable<double> diem6 { get; set; }
        public Nullable<double> diem7 { get; set; }
        public Nullable<double> diem8 { get; set; }
        public Nullable<double> diem9 { get; set; }
        public Nullable<double> diem10 { get; set; }
        public Nullable<double> diemtb { get; set; }
        public string diemchu { get; set; }
    }
}
