//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nganh
    {
        public int ID { get; set; }
        public string ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> bp_id { get; set; }
        public string Kyhieu { get; set; }
        public Nullable<int> capdaotao { get; set; }
        public Nullable<int> hedaotao { get; set; }
        public string MoTa { get; set; }
        public string Ghichu { get; set; }
        public Nullable<byte> Locked { get; set; }
    }
}
