//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhom_tienquyet
    {
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<int> id_hocphan { get; set; }
        public Nullable<int> id_khung { get; set; }
        public Nullable<sbyte> and { get; set; }
        public Nullable<sbyte> or { get; set; }
        public Nullable<int> id_loaihocphan { get; set; }
    }
}
