//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanhtoan_nganhang
    {
        public int ID { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<int> loai { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<double> Sotien { get; set; }
        public string Ghichu { get; set; }
    }
}
