//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thi
    {
        public int ID { get; set; }
        public Nullable<int> lophp_id { get; set; }
        public Nullable<int> nhomthi_id { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string gio { get; set; }
        public Nullable<int> phong_id { get; set; }
        public Nullable<int> cb1_id { get; set; }
        public Nullable<int> cb2_id { get; set; }
        public string Ghichu { get; set; }
    }
}
