//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thietlaphesodiemrl
    {
        public int id { get; set; }
        public Nullable<double> hocki1 { get; set; }
        public Nullable<double> hocki2 { get; set; }
        public Nullable<double> nam1 { get; set; }
        public Nullable<double> nam2 { get; set; }
        public Nullable<double> nam3 { get; set; }
        public Nullable<double> nam4 { get; set; }
        public Nullable<double> nam5 { get; set; }
    }
}
