//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thoikhoabieu
    {
        public int ID { get; set; }
        public string idlop { get; set; }
        public int tuan { get; set; }
        public int thu { get; set; }
        public Nullable<int> phong_id { get; set; }
        public int tietbd { get; set; }
        public int tiettk { get; set; }
    }
}
