//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thuchi
    {
        public int ID { get; set; }
        public Nullable<int> sv_id { get; set; }
        public string SoCT { get; set; }
        public Nullable<System.DateTime> NgayCT { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string Noidung { get; set; }
        public Nullable<int> nguoithu_id { get; set; }
        public string ListHP { get; set; }
        public Nullable<byte> loai { get; set; }
        public Nullable<byte> HocLai { get; set; }
        public string NoidungIn { get; set; }
        public string SoUNC { get; set; }
        public string SoTK { get; set; }
        public string maNH { get; set; }
        public Nullable<System.DateTime> NgayUNC { get; set; }
        public string GhiChu { get; set; }
        public string SotheSV { get; set; }
    }
}
