//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treeview
    {
        public int ID { get; set; }
        public Nullable<int> capdaotao { get; set; }
        public Nullable<int> hethongdt { get; set; }
        public string khoahoc { get; set; }
        public Nullable<int> nganh { get; set; }
        public string lop { get; set; }
    }
}
