//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_dangky_hp
    {
        public int ID { get; set; }
        public Nullable<int> lophp_id { get; set; }
        public Nullable<int> sv_id { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<bool> lan2 { get; set; }
        public Nullable<bool> Capnhat { get; set; }
        public Nullable<int> lophp_xoa_id { get; set; }
        public Nullable<int> hocphan_id { get; set; }
        public Nullable<bool> KhaoSat { get; set; }
        public Nullable<bool> Close { get; set; }
    }
}
