//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_thoigiandk
    {
        public int ID { get; set; }
        public string lophp_id { get; set; }
        public Nullable<System.DateTime> Ngay1 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> KhaoSat { get; set; }
        public Nullable<bool> Close { get; set; }
        public string hocphan_id { get; set; }
        public Nullable<int> namhoc_id { get; set; }
        public Nullable<int> hocky_id { get; set; }
    }
}
