//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_hoidap
    {
        public int ID { get; set; }
        public Nullable<int> Nhom_id { get; set; }
        public string hoi { get; set; }
        public Nullable<System.DateTime> tg_hoi { get; set; }
        public string dap { get; set; }
        public Nullable<System.DateTime> tg_dap { get; set; }
        public string IP { get; set; }
    }
}
