//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoTinChiCIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_tintuc
    {
        public int ID { get; set; }
        public Nullable<int> cb_id { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> batdau { get; set; }
        public Nullable<System.DateTime> hethan { get; set; }
        public Nullable<int> QuanTrong { get; set; }
    }
}
